# Generated by Django 5.0.6 on 2026-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowpattern",
            name="chunk_type",
            field=models.CharField(
                choices=[
                    ("scenario", "Scenario (intake + audit combined)"),
                    ("build", "Build documentation"),
                    ("reasoning", "Decision reasoning"),
                    ("outcome", "Outcome + delta"),
                    ("roadblock", "Individual roadblock"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="workflowpattern",
            index=models.Index(
                fields=["chunk_type", "workflow_type"],
                name="workflow_pa_chunk_t_e0d87f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowpattern",
            index=models.Index(
                fields=["satisfaction_score"], name="workflow_pa_satisfa_672a72_idx"
            ),
        ),
    ]
