# Generated by Django 5.0.6 on 2026-04-09 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_alter_workflowpattern_chunk_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("workflow_type", models.CharField(db_index=True, max_length=255)),
                ("industries", models.JSONField(default=list)),
                ("pain_points", models.JSONField(default=list)),
                ("tools", models.JSONField(default=list)),
                ("process_frameworks", models.JSONField(default=list)),
                ("spaces", models.TextField(blank=True)),
                ("lists", models.TextField(blank=True)),
                ("statuses", models.TextField(blank=True)),
                ("custom_fields", models.TextField(blank=True)),
                ("automations", models.TextField(blank=True)),
                ("integrations", models.JSONField(default=list)),
                ("build_notes", models.TextField(blank=True)),
                ("estimated_complexity", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "workflow_templates",
                "ordering": ["workflow_type", "name"],
            },
        ),
    ]
