# Generated by Django 5.0.6 on 2026-04-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_add_workflow_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtemplate",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowtemplate",
            name="source_project_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
