# Generated by Django 5.0.6 on 2026-04-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_user_id_6193b2_idx",
            old_name="audit_logs_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_created_43fcd6_idx",
            old_name="audit_logs_created_idx",
        ),
    ]
