# Generated by Django 5.0.6 on 2026-04-05 05:28

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0008_casefile_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="casefile",
            index=models.Index(
                fields=["satisfaction_score"], name="case_files_satisfa_f687bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casefile",
            index=models.Index(
                fields=["workflow_type"], name="case_files_workflo_71f015_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casefile",
            index=models.Index(
                fields=["team_size"], name="case_files_team_si_29d6ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casefile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["industries"], name="case_files_industr_1b5c7f_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="casefile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tools"], name="case_files_tools_21417a_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="roadblock",
            index=models.Index(
                fields=["severity"], name="roadblocks_severit_a873a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadblock",
            index=models.Index(
                fields=["flag_for_future"], name="roadblocks_flag_fo_cfd2d5_idx"
            ),
        ),
    ]
