# Generated by Django 5.0.6 on 2026-04-18 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0014_casefile_client_share_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pm", "Project Management"),
                            ("automation", "Automation / Integration"),
                            ("database", "Database / No-Code"),
                            ("crm", "CRM"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "concept_labels",
                    models.JSONField(
                        default=dict,
                        help_text="Maps generic concepts to platform terms, e.g. {'container': 'Space', 'workflow_group': 'Folder'}",
                    ),
                ),
                ("supported", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platforms",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="buildlayer",
            name="containers",
            field=models.JSONField(
                default=list,
                help_text="Top-level organisational units (Spaces in CU, Boards in Monday, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="AI confidence in data quality (0.0–1.0) for ingested case files",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="source_attribution",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="casefile",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("organic", "Direct user input"),
                    ("ingested", "AI-ingested from public source"),
                    ("community", "Community contribution"),
                    ("template", "Official template"),
                ],
                default="organic",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="source_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casefile",
            name="connected_platforms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other platforms integrated in this workflow",
                related_name="connected_case_files",
                to="briefs.platform",
            ),
        ),
        migrations.AddField(
            model_name="casefile",
            name="primary_platform",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary workflow platform being configured",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_files",
                to="briefs.platform",
            ),
        ),
        migrations.CreateModel(
            name="IntegrationPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("data_sync", "Data Sync"),
                            ("trigger_action", "Trigger → Action"),
                            ("bidirectional", "Bidirectional Sync"),
                            ("migration", "One-time Migration"),
                            ("webhook", "Webhook-based"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("known_limitations", models.JSONField(default=list)),
                ("workarounds", models.JSONField(default=list)),
                ("success_rate", models.FloatField(blank=True, null=True)),
                ("case_file_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_patterns",
                        to="briefs.platform",
                    ),
                ),
                (
                    "target_platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_patterns",
                        to="briefs.platform",
                    ),
                ),
                (
                    "via_platform",
                    models.ForeignKey(
                        blank=True,
                        help_text="Intermediary platform if not a native integration (e.g. Zapier, Make)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="middleware_patterns",
                        to="briefs.platform",
                    ),
                ),
            ],
            options={
                "db_table": "integration_patterns",
                "unique_together": {
                    ("source_platform", "target_platform", "pattern_type")
                },
            },
        ),
    ]
