# Generated by Django 5.0.6 on 2026-04-18 06:47

from django.db import migrations


# Map tool names (case-insensitive) that appear in CaseFile.tools to platform slugs.
# The first match wins, so order matters: platform-specific tools come before
# generic ones like "Slack" that don't indicate a primary platform.
TOOL_TO_PLATFORM = {
    "clickup": "clickup",
    "monday": "monday",
    "monday.com": "monday",
    "asana": "asana",
    "zapier": "zapier",
    "make": "make",
    "integromat": "make",
    "airtable": "airtable",
    "hubspot": "hubspot",
    "notion": "notion",
}

# Tools that represent connected integrations, not a primary platform.
CONNECTED_TOOL_MAP = {
    "slack": None,        # communication, not a workflow platform
    "google drive": None,
    "zoom": None,
    "loom": None,
    "figma": None,
    "docusign": None,
    "stripe": None,
    "github": None,
    "excel": None,
    "spreadsheets": None,
    "smartsheet": None,   # not yet in our Platform table
    "salesforce": None,
    "linear": None,
    "jira": None,
}


def backfill_primary_platform(apps, schema_editor):
    CaseFile = apps.get_model("briefs", "CaseFile")
    Platform = apps.get_model("briefs", "Platform")

    # Build a slug→Platform lookup
    platforms_by_slug = {p.slug: p for p in Platform.objects.all()}

    for cf in CaseFile.objects.filter(primary_platform__isnull=True):
        tools = cf.tools or []
        primary = None
        connected_slugs = []

        for tool in tools:
            tool_lower = tool.strip().lower()

            # Check if this tool maps to a primary platform
            slug = TOOL_TO_PLATFORM.get(tool_lower)
            if slug and slug in platforms_by_slug:
                if primary is None:
                    primary = platforms_by_slug[slug]
                else:
                    # Already have a primary — this one is a connected platform
                    connected_slugs.append(slug)
                continue

            # Check connected-tool map for known platforms that are integrations
            if tool_lower in CONNECTED_TOOL_MAP:
                continue

            # Unknown tool — skip (no platform record for it)

        if primary:
            cf.primary_platform = primary
            cf.save(update_fields=["primary_platform"])

        if connected_slugs:
            connected = Platform.objects.filter(slug__in=connected_slugs)
            cf.connected_platforms.add(*connected)


def reverse_backfill(apps, schema_editor):
    CaseFile = apps.get_model("briefs", "CaseFile")
    CaseFile.objects.update(primary_platform=None)
    # Clear M2M
    CaseFile.connected_platforms.through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0015_platform_and_ingestion_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_primary_platform, reverse_backfill),
    ]
