# Generated by Django 5.0.6 on 2026-04-18 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0016_backfill_casefile_primary_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="category",
            field=models.CharField(
                choices=[
                    ("pm", "Project Management"),
                    ("automation", "Automation / Integration"),
                    ("database", "Database / No-Code"),
                    ("crm", "CRM"),
                    ("integration_app", "Integration App"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CommunityInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("methodology", "Methodology"),
                            ("workaround", "Workaround"),
                            ("complaint", "Complaint / Pain Point"),
                            ("best_practice", "Best Practice"),
                            ("feature_request", "Feature Request"),
                            ("gotcha", "Gotcha / Pitfall"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("source_url", models.URLField(blank=True, default="")),
                (
                    "source_attribution",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'ZenPilot', 'ClickUp Community', 'Reddit r/clickup'",
                        max_length=255,
                    ),
                ),
                (
                    "source_date",
                    models.DateField(
                        blank=True, help_text="When the source was published", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Reliability: official docs (0.9+) > practitioner blog (0.7) > forum post (0.5)",
                        null=True,
                    ),
                ),
                (
                    "applies_to_industries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Industry tags if this insight is industry-specific",
                    ),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platforms",
                    models.ManyToManyField(
                        help_text="Platforms this insight relates to",
                        related_name="community_insights",
                        to="briefs.platform",
                    ),
                ),
            ],
            options={
                "db_table": "community_insights",
                "ordering": ["-source_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["insight_type"], name="community_i_insight_2f87a5_idx"
                    ),
                    models.Index(
                        fields=["source_date"], name="community_i_source__db5f33_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("capability", "Capability"),
                            ("limitation", "Limitation"),
                            ("pricing_constraint", "Pricing Constraint"),
                            ("api_detail", "API Detail"),
                            ("integration_spec", "Integration Spec"),
                            ("feature", "Feature"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("automations", "Automations"),
                            ("integrations", "Integrations"),
                            ("permissions", "Permissions"),
                            ("hierarchy", "Hierarchy / Structure"),
                            ("reporting", "Reporting / Dashboards"),
                            ("views", "Views"),
                            ("custom_fields", "Custom Fields"),
                            ("templates", "Templates"),
                            ("api", "API"),
                            ("pricing", "Pricing / Plans"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("source_url", models.URLField(blank=True, default="")),
                ("source_attribution", models.CharField(blank=True, max_length=255)),
                (
                    "verified_at",
                    models.DateField(
                        blank=True,
                        help_text="Date this was last confirmed accurate",
                        null=True,
                    ),
                ),
                (
                    "platform_version",
                    models.CharField(
                        blank=True,
                        help_text="Platform version if version-specific, e.g. 'ClickUp 3.0'",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0–1.0 confidence in accuracy",
                        null=True,
                    ),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="briefs.platform",
                    ),
                ),
                (
                    "related_platform",
                    models.ForeignKey(
                        blank=True,
                        help_text="Second platform if this is about an integration pair",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_knowledge",
                        to="briefs.platform",
                    ),
                ),
            ],
            options={
                "db_table": "platform_knowledge",
                "ordering": ["-verified_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "knowledge_type"],
                        name="platform_kn_platfor_2aeba3_idx",
                    ),
                    models.Index(
                        fields=["platform", "category"],
                        name="platform_kn_platfor_cf699c_idx",
                    ),
                    models.Index(
                        fields=["platform", "related_platform"],
                        name="platform_kn_platfor_41891a_idx",
                    ),
                ],
            },
        ),
    ]
