# Generated by Django 5.0.6 on 2026-04-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0017_platform_knowledge_and_community_insights"),
    ]

    operations = [
        migrations.AddField(
            model_name="casefile",
            name="is_training_data",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for ingested/training case files; False for client project work",
            ),
        ),
    ]
