# Generated by Django 5.0.6 on 2026-04-18 08:08

from django.db import migrations


def backfill_training_flag(apps, schema_editor):
    """Mark all ingested case files as training data."""
    CaseFile = apps.get_model("briefs", "CaseFile")
    CaseFile.objects.filter(
        source_type="ingested", is_training_data=False
    ).update(is_training_data=True)


def reverse(apps, schema_editor):
    CaseFile = apps.get_model("briefs", "CaseFile")
    CaseFile.objects.filter(is_training_data=True).update(is_training_data=False)


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0018_casefile_is_training_data"),
    ]

    operations = [
        migrations.RunPython(backfill_training_flag, reverse),
    ]
