# Generated by Django 5.0.6 on 2026-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0019_backfill_is_training_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casefile",
            name="is_training_data",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True for ingested-only training data (hidden from project list); False for user-created projects (visible in project list). Both are used by the AI recommendation engine.",
            ),
        ),
    ]
