# Generated by Django 5.0.6 on 2026-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0023_billingshare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingshare",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
