# Generated by Django 5.0.6 on 2026-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0024_alter_billingshare_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="casefile",
            name="header_summary",
            field=models.TextField(blank=True),
        ),
    ]
